export const THEME_KEY = "V-THEME-KEY";
export const ACCESS_TOKEN_KEY = "ACCESS_TOKEN";
export const REFRESH_TOKEN_KEY = "REFRESH_TOKEN"
export const ROLE_KEY = "ROLE_KEY";
export const REMEMBER_USER_CREDENTIALS_WHEN_LOGIN_KEY = "USER_CREDENTIALS";
export const CATEGORY_SESSION_KEY = "CATEGORY_SESSION_KEY"
export const USER_KEY = "USER_KEY"

