export enum Roles {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  POS_USER = "POS_USER",
  KITCHEN_STAFF = "KITCHEN_STAFF",
  WAITER = "WAITER",
}

export enum PRODUCT_TYPE_ENUMS{
  SINGLE = "SINGLE",
  COMBO = "COMBO"
  
}
